[package]
name = "tetanus_client"
version = "0.1.0"
edition = "2024"

[dependencies]
chacha20poly1305 = "0.10.1"
clap = { version = "4.5.51", features = ["derive"] }
colored = "3.0.0"
dns-lookup = "3.0.1"
num_cpus = "1.17.0"
tokio = { version = "1.48.0", features = ["full"] }
walkdir = "2.5.0"
